function DisableAll(){
  tempInfoMenor.setAttribute('disabled'," ");
  tempInfoMenor.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoResponsavel.setAttribute('disabled'," ");
  tempInfoResponsavel.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoCpfresp.setAttribute('disabled'," ");
  tempInfoCpfresp.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoCpf.setAttribute('disabled'," ");
  tempInfoCpf.setAttribute('style','background-color: #333; border-color: #777')
  tempInfoCns.setAttribute('disabled'," ");
  tempInfoCns.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoRegistro.setAttribute('disabled'," ");
  tempInfoRegistro.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoNacionalidade.setAttribute('disabled'," ");
  tempInfoNacionalidade.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoNascimento.setAttribute('disabled'," ");
  tempInfoNascimento.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoGenero.setAttribute('disabled'," ");
  tempInfoGenero.setAttribute('style','width: 80px; border-color: #777'); // backgroud-color on w2ui-1.5.rc1.css  line 1449
  tempInfoTel.setAttribute('disabled'," ");
  tempInfoTel.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoCel.setAttribute('disabled'," ");
  tempInfoCel.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoWhatsapp.setAttribute('disabled'," ");
  tempInfoWhatsapp.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoEmail.setAttribute('disabled'," ");
  tempInfoEmail.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoEndereco.setAttribute('disabled'," ");
  tempInfoEndereco.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoCep.setAttribute('disabled'," ");
  tempInfoCep.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoBairro.setAttribute('disabled'," ");
  tempInfoBairro.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoUf.setAttribute('disabled'," ");
  tempInfoUf.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoCidade.setAttribute('disabled'," ");
  tempInfoCidade.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoHistorico.setAttribute('disabled'," ");
  tempInfoHistorico.setAttribute('style','background-color: #333; width: 300px; height:60px; border-color: #777');
  tempInfoMedicamento.setAttribute('disabled'," ");
  tempInfoMedicamento.setAttribute('style','background-color: #333; width: 300px; height:60px; border-color: #777');
  tempInfoCirurgia.setAttribute('disabled'," ");
  tempInfoCirurgia.setAttribute('style','background-color: #333; width: 300px; height:60px; border-color: #777');
  tempInfoTrauma.setAttribute('disabled'," ");
  tempInfoTrauma.setAttribute('style','background-color: #333; width: 300px; height:60px; border-color: #777');
  tempInfoAtivo.setAttribute('disabled'," ");
  tempInfoAtivo.setAttribute('style','background-color: #333; border-color: #777');
  tempInfoFormulario.setAttribute('disabled'," ");
  tempInfoFormulario.setAttribute('style','background-color: #333; border-color: #777; width: 150px');
  buttonGravar.setAttribute('disabled'," ");
  buttonDescartar.setAttribute('disabled'," ");
}

function ClearData(){
  headerForm.textContent = '';
  tempInfoNome.value = '';
  tempInfoNome.removeAttribute('style'); 
  tempInfoMenor.checked=false;
  tempInfoResponsavel.value = '';
  tempInfoCpfresp.value = '';
  tempInfoCpf.value = '';
  tempInfoCns.value = '';
  tempInfoRegistro.value = '';
  tempInfoNacionalidade.value = '';
  tempInfoNascimento.value = '';
  tempInfoGenero.value = '';
  tempInfoTel.value = '';
  tempInfoCel.value = '';
  tempInfoWhatsapp.checked=false;
  tempInfoEmail.value = '';
  tempInfoEndereco.value = '';
  tempInfoCep.value = '';
  tempInfoBairro.value = '';
  tempInfoUf.value = '';
  tempInfoCidade.value = '';
  tempInfoHistorico.value = '';
  tempInfoMedicamento.value = '';
  tempInfoCirurgia.value = '';
  tempInfoTrauma.value = '';
  tempInfoFormulario.value = '';
}

function EnableAll(){
  tempInfoMenor.removeAttribute('disabled');
  tempInfoMenor.removeAttribute('style');
  tempInfoCpf.removeAttribute('disabled');
  tempInfoCpf.removeAttribute('style');
  tempInfoCns.removeAttribute('disabled');
  tempInfoCns.removeAttribute('style');
  tempInfoRegistro.removeAttribute('disabled');
  tempInfoRegistro.removeAttribute('style');
  tempInfoNacionalidade.removeAttribute('disabled');
  tempInfoNacionalidade.removeAttribute('style');
  tempInfoNascimento.removeAttribute('disabled');
  tempInfoNascimento.removeAttribute('style');
  tempInfoGenero.removeAttribute('disabled');
  tempInfoGenero.removeAttribute('style');
  tempInfoGenero.setAttribute('style','width: 80px');
  tempInfoTel.removeAttribute('disabled');
  tempInfoTel.removeAttribute('style');
  tempInfoCel.removeAttribute('disabled');
  tempInfoCel.removeAttribute('style');
  tempInfoWhatsapp.removeAttribute('disabled');
  tempInfoWhatsapp.removeAttribute('style');
  tempInfoEmail.removeAttribute('disabled');
  tempInfoEmail.removeAttribute('style');
  tempInfoEndereco.removeAttribute('disabled');
  tempInfoEndereco.removeAttribute('style');
  tempInfoCep.removeAttribute('disabled');
  tempInfoCep.removeAttribute('style');
  tempInfoBairro.removeAttribute('disabled');
  tempInfoBairro.removeAttribute('style');
  tempInfoUf.removeAttribute('disabled');
  tempInfoUf.removeAttribute('style');
  tempInfoCidade.removeAttribute('disabled');
  tempInfoCidade.removeAttribute('style');
  tempInfoHistorico.removeAttribute('disabled');
  tempInfoHistorico.removeAttribute('style');
  tempInfoHistorico.setAttribute('style','width: 300px; height:60px');
  tempInfoMedicamento.removeAttribute('disabled');
  tempInfoMedicamento.removeAttribute('style');
  tempInfoMedicamento.setAttribute('style','width: 300px; height:60px');
  tempInfoCirurgia.removeAttribute('disabled');
  tempInfoCirurgia.removeAttribute('style');
  tempInfoCirurgia.setAttribute('style','width: 300px; height:60px');
  tempInfoTrauma.removeAttribute('disabled');
  tempInfoTrauma.removeAttribute('style');
  tempInfoTrauma.setAttribute('style','width: 300px; height:60px');
  tempInfoAtivo.removeAttribute('disabled');
  tempInfoAtivo.removeAttribute('style');
  tempInfoFormulario.removeAttribute('disabled');
  tempInfoFormulario.setAttribute('style','width: 150px;');
  buttonGravar.removeAttribute('disabled');
  buttonDescartar.removeAttribute('disabled');
}

function ClearDataMinusNome(){
  tempInfoNome.removeAttribute('style'); 
  tempInfoMenor.checked=false;
  tempInfoResponsavel.value = '';
  tempInfoCpfresp.value = '';
  tempInfoCpf.value = '';
  tempInfoCns.value = '';
  tempInfoRegistro.value = '';
  tempInfoNacionalidade.value = '';
  tempInfoNascimento.value = '';
  tempInfoGenero.value = '';
  tempInfoTel.value = '';
  tempInfoCel.value = '';
  tempInfoWhatsapp.checked=false;
  tempInfoEmail.value = '';
  tempInfoEndereco.value = '';
  tempInfoCep.value = '';
  tempInfoBairro.value = '';
  tempInfoUf.value = '';
  tempInfoCidade.value = '';
  tempInfoHistorico.value = '';
  tempInfoMedicamento.value = '';
  tempInfoCirurgia.value = '';
  tempInfoTrauma.value = '';
  tempInfoFormulario.value = '';
}
